# Exemplo simplificado de configuração de papéis
roles:
    atacante:
      default_behavior: "attack"
      speed_factor: 1.0
    goleiro:
      default_behavior: "defend"
      speed_factor: 0.5
    zagueiro:
      default_behavior: "cover"
      speed_factor: 0.8
  